image: node:20

stages:
  - deploy

vercel-production:
  stage: deploy
  only:
    - main
  script:
    - npm i -g vercel
    # Pull the Vercel Project Configuration
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    # Trigger Vercel to build and deploy the app using its own environment variables
    - vercel deploy --prod --token=$VERCEL_TOKEN
